# framework/render/vulkan/cmake/optical_flow_shaders.cmake
# Emit the COMPLETE set of SPIR-V headers that src/OpticalFlowPipeline.cpp #includes.
# Single source of truth for the optical-flow shader-header set: the standalone benches
# (and the render_assistant app) that compile OpticalFlowPipeline.cpp directly each have to
# generate these headers themselves; keeping the list in ONE place means a future shader
# #include added to the pipeline cannot silently break N consumers. The set tracks
# src/OpticalFlowPipeline.cpp:83-87 — verify first-hand if you change the pipeline's #includes.
#
# Usage from a bench / app CMakeLists (after its own find_program(<GLSLC>) has succeeded):
#   set(_render_vulkan "${CMAKE_CURRENT_SOURCE_DIR}/../..")        # framework/render/vulkan
#   include("${_render_vulkan}/cmake/optical_flow_shaders.cmake")
#   phyriad_optical_flow_shader_headers(
#       GLSLC       "${STAGEnn_GLSLC}"        # the resolved glslc path
#       RENDER_VK   "${_render_vulkan}"       # framework/render/vulkan root
#       GEN_DIR     "${_gen_dir}"             # where the *_spv.hpp are written (on the include path)
#       OUT_HEADERS _ofp_headers)             # set, in PARENT_SCOPE, to the generated header paths
#   add_custom_target(stageNN_shaders DEPENDS ${_ofp_headers} <this consumer's own headers>)
#   add_executable(stageNN main.cpp "${_render_vulkan}/src/OpticalFlowPipeline.cpp")
#   add_dependencies(stageNN stageNN_shaders)
#
# Mirrors the per-bench glslc -> .spv -> spv_to_header.cmake -> .hpp rule byte-for-byte
# (--target-env=vulkan1.2 -O), so adopting it leaves the generated bytecode identical. NOTE:
# this covers ONLY the headers OpticalFlowPipeline.cpp #includes; a consumer that also drives
# the block-match baseline (optical_flow_block_match) keeps generating that one itself.

function(phyriad_optical_flow_shader_headers)
    cmake_parse_arguments(_OFP "" "GLSLC;RENDER_VK;GEN_DIR;OUT_HEADERS" "" ${ARGN})
    if(NOT _OFP_GLSLC OR NOT _OFP_RENDER_VK OR NOT _OFP_GEN_DIR OR NOT _OFP_OUT_HEADERS)
        message(FATAL_ERROR
            "phyriad_optical_flow_shader_headers: requires GLSLC, RENDER_VK, GEN_DIR, OUT_HEADERS")
    endif()
    set(_spv2hdr "${_OFP_RENDER_VK}/cmake/spv_to_header.cmake")
    # The exact set src/OpticalFlowPipeline.cpp #includes (lines 83-87). "<stem>|<VARNAME>"
    # — a '|' delimiter, NOT ';' (an embedded ';' would flatten the CMake list).
    set(_ofp_shaders
        "optical_flow_pyr_down|kOpticalFlowPyrDownSpv"
        "optical_flow_hier_match|kOpticalFlowHierMatchSpv"
        "optical_flow_hier_match_fg|kOpticalFlowHierMatchFgSpv"   # CANON #12 FG-variant fork
        "optical_flow_warp|kOpticalFlowWarpSpv"
        "optical_flow_affine_fit|kOpticalFlowAffineFitSpv")       # ARC-A LEVER-1 affine post-pass
    set(_headers "")
    foreach(_entry IN LISTS _ofp_shaders)
        string(REPLACE "|" ";" _pair "${_entry}")
        list(GET _pair 0 _stem)
        list(GET _pair 1 _var)
        set(_src "${_OFP_RENDER_VK}/shaders/${_stem}.comp")
        set(_spv "${_OFP_GEN_DIR}/${_stem}.spv")
        set(_hdr "${_OFP_GEN_DIR}/${_stem}_spv.hpp")
        add_custom_command(OUTPUT "${_spv}"
            COMMAND ${CMAKE_COMMAND} -E make_directory "${_OFP_GEN_DIR}"
            COMMAND "${_OFP_GLSLC}" --target-env=vulkan1.2 -O "${_src}" -o "${_spv}"
            DEPENDS "${_src}" COMMENT "glslc ${_stem}" VERBATIM)
        add_custom_command(OUTPUT "${_hdr}"
            COMMAND ${CMAKE_COMMAND} -D "INPUT=${_spv}" -D "OUTPUT=${_hdr}"
                    -D "VARNAME=${_var}" -P "${_spv2hdr}"
            DEPENDS "${_spv}" "${_spv2hdr}" COMMENT "spv -> header: ${_var}" VERBATIM)
        list(APPEND _headers "${_hdr}")
    endforeach()
    set(${_OFP_OUT_HEADERS} "${_headers}" PARENT_SCOPE)
endfunction()
# Made with my soul - Swately <3
